apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9zYW1heWd1cHRhOnNhbWF5MTIzQGNsdXN0ZXIwLjZwY215NDUubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
 
